import esbuild from "esbuild";
import process from "process";
// import sveltePlugin from "esbuild-svelte";
// import sveltePreprocess from "svelte-preprocess";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
https://github.com/joethei/obsidian-calibre
*/
`;

const prod = process.argv[2] === "production";

esbuild
	.build({
		banner: {
			js: banner,
		},
		entryPoints: ["src/main.ts"],
		bundle: true,

		external: [
			"obsidian",
			"electron",
			"codemirror"
		],
		format: "cjs",
		platform: "browser",
		watch: !prod,
		target: "es2021",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outfile: "main.js",
		plugins: [
			//   sveltePlugin({
			//     compilerOptions: { css: true },
			//     preprocess: sveltePreprocess(),
			//   }),
		],
	})
	.catch(() => process.exit(1));
