name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: yarn
            - name: Lint
              run: yarn run lint
            - name: Lint CSS
              run: yarn run lint-css
            - name: Test
              run: yarn run test
